// <auto-generated />
using System;
using Blazor.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826192033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("Blazor.API.Features.Produtos.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0832ba9b-8ff1-46de-9f1e-ee33776af904"),
                            Categoria = "Categoria A",
                            DataCriacao = new DateTime(2026, 8, 26, 19, 20, 32, 738, DateTimeKind.Utc).AddTicks(1164),
                            Nome = "Produto 1",
                            Preco = 10.99m,
                            QuantidadeEstoque = 100
                        },
                        new
                        {
                            Id = new Guid("e57736c7-67ea-47ac-8127-3d3257b9c089"),
                            Categoria = "Categoria B",
                            DataCriacao = new DateTime(2026, 8, 26, 19, 20, 32, 738, DateTimeKind.Utc).AddTicks(1190),
                            Nome = "Produto 2",
                            Preco = 20.50m,
                            QuantidadeEstoque = 50
                        },
                        new
                        {
                            Id = new Guid("b35f8970-f1a0-4aaf-9ebe-ce754cb7aedd"),
                            Categoria = "Categoria A",
                            DataCriacao = new DateTime(2026, 8, 26, 19, 20, 32, 738, DateTimeKind.Utc).AddTicks(1192),
                            Nome = "Produto 3",
                            Preco = 15.75m,
                            QuantidadeEstoque = 75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
